### ISSUE TITLE
Issue integrating this with other middleware such as koa-passport

### ISSUE THREAD

**Issue by deankarn** [tunnckoCore/koa-better-body#1]
after much research the root of the issue seems to be that passport-local looks for fields directly of of the koa body object i.e. this.request.body

but because this plugin sets the fields on this.request.body.fields, passport-local thinks there are none and authentication fails.

would it be possible to set the fields on the body itself i.e. this.request.body = form.parse...or json.parse

and to avoid the naming conflict of the files set that on the request object itself?

I have noticed that most other body parsers set the fields in the body itself.

**Comment by imkimchi** [comment]
@joeybloggs It's pretty old issue but I'm wondering how you got it work with passport, as I'm using passport-local as well.

I just changed `fields` option to `body` to get this work but seems like there are some more issues over that

**Comment by tunnckoCore** [comment]
> but seems like there are some more issues over that

What issues? But in anyway, [passport-local](https://github.com/jaredhanson/passport-local) seems to be very outdated. Use [simov/grant](https://github.com/simov/grant), it's pretty fantastic for such things. A lot better than Passport et all, and even any other auth thing out there.

**Comment by deankarn** [comment]
Haven't used nodejs in quite some time sorry, do know that I ever got it to work
