### ISSUE TITLE
npm i koa-better-body is install error

### ISSUE THREAD

**Issue by Hjaeiwi** [tunnckoCore/koa-better-body#243]
In install koa-better-body,i use npm i koa-better-body an error occurred，unable to install

**Comment by tunnckoCore** [comment]
Hey there. Cleaning up the mess around my repositories and issues.

What version of node? What version of `koa-better-body`? I don't have problem installing the current `latest` which is 3.3.9.

You probably tried some older one, when the link of the package was pointing to this repository.

It resides on https://github.com/tunnckoCore/opensource for quite some time.

I don't remember what I did, but seems like this repository was the main koa-better-body one, then migrated all its commits, issues and tags to the `opensource` repo.

<blockquote><img src="https://repository-images.githubusercontent.com/80710714/e8c47300-0c5a-11ea-91c5-acea4cf9f18f" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tunnckoCore/opensource">GitHub - tunnckoCore/opensource: Delivering delightful digital solutions. Monorepo of monorepos of Open Source packages with combined ~100M/month downloads, semantically versioned following @conventional-commits. Fully powered ES Modules, @Airbnb @ESLint + @Prettier, independent & fixed versioning. Quality with @Actions, CodeQL, & Dependabot.</a></strong></div><div>Delivering delightful digital solutions. Monorepo of monorepos of Open Source packages with combined ~100M/month downloads, semantically versioned following @conventional-commits. Fully powered ES ...</div></blockquote>
